####################
# openwallet
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "openwallet",
 "params":[
  "wallet.json",
  "neo"
  ],
 "id": 1
}

####################
# sendtoaddress
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "sendtoaddress",
 "params": [
  "0xde5f57d430d3dece511cf975a8d37848cb9e0525",
  "AJunErzotcQTNWP2qktA7LgkXZVdHea97H",
  100
 ],
 "id": 1
}

####################
# listaddress
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "listaddress",
 "params": [],
 "id": 1
}

####################
# sendfrom
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "sendfrom",
 "params": [
  "0xde5f57d430d3dece511cf975a8d37848cb9e0525",
  "AGZLEiwUyCC4wiL5sRZA3LbxWPs9WrZeyN",
  "AJunErzotcQTNWP2qktA7LgkXZVdHea97H",
  "100.0"
 ],
 "id": 1
}

####################
# sendmany
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "sendmany",
 "params": [
   "AVGpjFiocR1BdYhbYWqB6Ls6kcmzx4FWhm",
   [
     {
       "asset": "0xde5f57d430d3dece511cf975a8d37848cb9e0525",
       "value": 10,
       "address": "AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y"
     }
   ],
   "1"
 ],
 "id": 1
}

####################
# getbalance
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "getnep17balances",
 "params": [
  "AGZLEiwUyCC4wiL5sRZA3LbxWPs9WrZeyN", 0
 ],
 "id": 1
}

####################
# getapplicationlog
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "getapplicationlog",
 "params": [
  "0x01bcf2edbd27abb8d660b6a06113b84d02f635fed836ce46a38b4d67eae80109"
 ],
 "id": 1
}

####################
# getblockcount
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "getblockcount",
 "params": [ ],
 "id": 1
}

####################
# sendrawtransaction
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "sendrawtransaction",
 "params": [ "00fde9020c00fea46931b5c22a99277a25233ff431d642b855c27289000000000088442400000000009f1420000101941343239213fa0e765f1027ce742f48db779a96015600640c14e6c1013654af113d8a968bdca52c9948a82b953d0c14941343239213fa0e765f1027ce742f48db779a9613c00c087472616e736665720c14897720d8cd76f4f00abfa37c0edd889c208fde9b41627d5b523802420c40b7e850a00d6184b3a9ce405ea4913c6a2790c5eb7230103c6cd978ce5a118c0fa37006ee6e1c42086189fa5a1f66e7ddeae977e024a2c181397345da9f6622762b110c2102c0b60c995bc092e866f15a37c176bb59b7ebacf069ba94c0ebf561cb8f956238110b41c330181e420c40afc6c138eadf472826f64b410a45e4c917af3acedfa0ccacdc2641024d28d307d1619564d65bb485edd258b54ae0840e16e01bfbcb5b0ca6b06f13c1b56a3a02290c2102c0b60c995bc092e866f15a37c176bb59b7ebacf069ba94c0ebf561cb8f9562380b418a6b1e75" ],
 "id": 1
}

####################
# getrawtransaction
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "getrawtransaction",
 "params": [ "0x508c11ed02e31cec8d05df60efe3bb52fb7349b487033e5f4d8fea132489b2eb", 0 ],
 "id": 1
}

####################
# getblock
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "getblock",
 "params": [ 32, 1 ],
 "id": 1
}

####################
# invokefunction - getNextBlockValidators
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "invokefunction",
 "params": [ "de5f57d430d3dece511cf975a8d37848cb9e0525", "getNextBlockValidators" ],
 "id": 1
}

####################
# PolicyContract - getMaxTransactionsPerBlock
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "invokefunction",
 "params": [ "3209d09120465bf181ced70693b897ec6ea4619a", "getMaxTransactionsPerBlock" ],
 "id": 1
}

####################
# PolicyContract - getFeePerByte
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "invokefunction",
 "params": [ "3209d09120465bf181ced70693b897ec6ea4619a", "getFeePerByte" ],
 "id": 1
}

####################
# PolicyContract - getBlockedAccounts
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "invokefunction",
 "params": [ "ce06595079cd69583126dbfd1d2e25cca74cffe9", "getBlockedAccounts" ],
 "id": 1
}

####################
# PolicyContract - setMaxTransactionsPerBlock
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "invokefunction",
 "params": [ "3209d09120465bf181ced70693b897ec6ea4619a", "setMaxTransactionsPerBlock",
   [
     {"type": "Integer", "value": 256}
   ],
   ["55b842d631f43f23257a27992ac2b53169a4fe00"]
 ],
 "id": 1
}

####################
# PolicyContract - blockAccount
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "invokefunction",
 "params": [ "3209d09120465bf181ced70693b897ec6ea4619a", "blockAccount",
   [
     {"type": "Hash160", "value": "df133e846b1110843ac357fc8bbf05b4a32e17c8"}
   ],
   ["55b842d631f43f23257a27992ac2b53169a4fe00"]
 ],
 "id": 1
}

####################
# invokefunction - vote
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "invokefunction",
 "params": [
   "0xde5f57d430d3dece511cf975a8d37848cb9e0525",
   "vote",
   [
     {"type": "Hash160", "value": "0xdf133e846b1110843ac357fc8bbf05b4a32e17c8"},
     {"type": "PublicKey", "value": "02200284598c6c1117f163dd938a4c8014cf2cf1164c4b7197f347109db50eae7c"},
     {"type": "PublicKey", "value": "02c0b60c995bc092e866f15a37c176bb59b7ebacf069ba94c0ebf561cb8f956238"}
   ],
   ["0xdf133e846b1110843ac357fc8bbf05b4a32e17c8"]
 ],
 "id": 1
}

####################
# invokefunction - registerCandidate
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "invokefunction",
 "params": [
   "de5f57d430d3dece511cf975a8d37848cb9e0525",
   "registerCandidate",
   [
     {"type": "PublicKey", "value": "02c0b60c995bc092e866f15a37c176bb59b7ebacf069ba94c0ebf561cb8f956238"}
   ],
   ["969a77db482f74ce27105f760efa139223431394"]
 ],
 "id": 1
}

####################
# invokefunction - getCandidates
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "invokefunction",
 "params": [
	 "0xde5f57d430d3dece511cf975a8d37848cb9e0525",
	 "getCandidates"
 ],
 "id": 1
}

####################
# invokefunction - getSymbol
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "invokefunction",
 "params": [
	 "0xde5f57d430d3dece511cf975a8d37848cb9e0525",
	 "symbol"
 ],
 "id": 1
}

####################
# invokefunction - getBalance
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "invokefunction",
 "params": [
   "0xde5f57d430d3dece511cf975a8d37848cb9e0525",
   "balanceOf",
   [
     {"type": "Hash160", "value": "0x3d952ba848992ca5dc8b968a3d11af543601c1e6"}
   ]
 ],
 "id": 1
}

####################
# invokefunction - transfer
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "invokefunction",
 "params":[
  "0xde5f57d430d3dece511cf975a8d37848cb9e0525",
  "transfer",
  [
    {"type": "Hash160", "value": "0x3d952ba848992ca5dc8b968a3d11af543601c1e6"},
    {"type": "Hash160", "value": "0xf68f181731a47036a99f04dad90043a744edec0f"},
    {"type": "Integer", "value": "1"}
  ],
  ["0x3d952ba848992ca5dc8b968a3d11af543601c1e6"]
  ],
 "id": 1
}

####################
# getcontractstate
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
  "jsonrpc": "2.0",
  "method": "getcontractstate",
  "params":["0xf61eebf573ea36593fd43aa150c055ad7906ab83"],
  "id": 1
}

####################
# getstorage
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
 "jsonrpc": "2.0",
 "method": "getstorage",
 "params": [
	 "0xde5f57d430d3dece511cf975a8d37848cb9e0525",
	 "14941343239213fa0e765f1027ce742f48db779a96"
 ],
 "id": 1
}

####################
# gettransactionheight
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
  "jsonrpc": "2.0",
  "method": "gettransactionheight",
  "params":["0x68b30037e53280c8c687cae33013b177aa7fe7339d932d2beaff84cf098e4f0b"],
  "id": 1
}

####################
# getnewaddress
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
  "jsonrpc": "2.0",
  "method": "getnewaddress",
  "params":[],
  "id": 1
}

####################
# importprivkey
####################
POST http://localhost:40332
Content-Type: application/javascript'

{
  "jsonrpc": "2.0",
  "method": "importprivkey",
  "params":["KwYRSjqmEhK4nPuUZZz1LEUSxvSzSRCv3SVePoe67hjcdPGLRJY5"],
  "id": 1
}

###
