package io.neow3j.devpack.constants;

/**
 * Enumerates all the interoperability services that a neo-node should provide to the NeoVM execution environment.
 * These services can be used in smart contract code via the {@link OpCode#SYSCALL} instruction.
 */
public enum InteropService {
    SYSTEM_CRYPTO_CHECKSIG,
    SYSTEM_CRYPTO_CHECKMULTISIG,
    SYSTEM_CONTRACT_CALL,
    SYSTEM_CONTRACT_CALLNATIVE,
    SYSTEM_CONTRACT_GETCALLFLAGS,
    SYSTEM_CONTRACT_CREATESTANDARDACCOUNT,
    SYSTEM_CONTRACT_CREATEMULTISIGACCOUNT,
    SYSTEM_CONTRACT_NATIVEONPERSIST,
    SYSTEM_CONTRACT_NATIVEPOSTPERSIST,
    SYSTEM_ITERATOR_NEXT,
    SYSTEM_ITERATOR_VALUE,
    SYSTEM_RUNTIME_PLATFORM,
    SYSTEM_RUNTIME_GETTRIGGER,
    SYSTEM_RUNTIME_GETTIME,
    SYSTEM_RUNTIME_GETSCRIPTCONTAINER,
    SYSTEM_RUNTIME_GETEXECUTINGSCRIPTHASH,
    SYSTEM_RUNTIME_GETCALLINGSCRIPTHASH,
    SYSTEM_RUNTIME_GETENTRYSCRIPTHASH,
    SYSTEM_RUNTIME_LOADSCRIPT,
    SYSTEM_RUNTIME_CHECKWITNESS,
    SYSTEM_RUNTIME_GETINVOCATIONCOUNTER,
    SYSTEM_RUNTIME_LOG,
    SYSTEM_RUNTIME_NOTIFY,
    SYSTEM_RUNTIME_GETNOTIFICATIONS,
    SYSTEM_RUNTIME_GASLEFT,
    SYSTEM_RUNTIME_BURNGAS,
    SYSTEM_RUNTIME_CURRENTSIGNERS,
    SYSTEM_RUNTIME_GETNETWORK,
    SYSTEM_RUNTIME_GETRANDOM,
    SYSTEM_STORAGE_GETCONTEXT,
    SYSTEM_STORAGE_GETREADONLYCONTEXT,
    SYSTEM_STORAGE_ASREADONLY,
    SYSTEM_STORAGE_GET,
    SYSTEM_STORAGE_FIND,
    SYSTEM_STORAGE_PUT,
    SYSTEM_STORAGE_DELETE,
    DUMMY;
}
