name: neow3j-integration

on:
  pull_request:
    types: [ assigned, review_requested, ready_for_review ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '8'
#          cache: 'gradle'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_PAT_USERNAME }}
          password: ${{ secrets.CR_PAT }}
      - name: Build with Integration Tests
        run: ./gradlew --info --warning-mode=all clean integrationTest